import { db, wilayasTable, categoriesTable, storesTable, listingsTable } from "@workspace/db";

async function seed() {
  const seedMode = process.env.SEED_MODE === "bootstrap" ? "bootstrap" : "reset";
  console.log(`🌱 Seeding Dzaïr Marketplace database in ${seedMode} mode...`);

  if (seedMode === "bootstrap") {
    const existing = await db.select().from(storesTable).limit(1);
    if (existing.length > 0) {
      console.log("Bootstrap seed skipped; stores already present");
      return;
    }
  }

  if (seedMode === "reset") {
    await db.delete(listingsTable);
    await db.delete(storesTable);
    await db.delete(categoriesTable);
    await db.delete(wilayasTable);
  }

  // Seed Wilayas
  const wilayas = await db.insert(wilayasTable).values([
    { code: 1, name: "Adrar", nameAr: "أدرار", region: "Sud" },
    { code: 2, name: "Chlef", nameAr: "الشلف", region: "Centre" },
    { code: 3, name: "Laghouat", nameAr: "الأغواط", region: "Centre" },
    { code: 4, name: "Oum El Bouaghi", nameAr: "أم البواقي", region: "Est" },
    { code: 5, name: "Batna", nameAr: "باتنة", region: "Est" },
    { code: 6, name: "Béjaïa", nameAr: "بجاية", region: "Centre" },
    { code: 7, name: "Biskra", nameAr: "بسكرة", region: "Sud" },
    { code: 8, name: "Béchar", nameAr: "بشار", region: "Sud" },
    { code: 9, name: "Blida", nameAr: "البليدة", region: "Centre" },
    { code: 10, name: "Bouira", nameAr: "البويرة", region: "Centre" },
    { code: 11, name: "Tamanrasset", nameAr: "تمنراست", region: "Sud" },
    { code: 12, name: "Tébessa", nameAr: "تبسة", region: "Est" },
    { code: 13, name: "Tlemcen", nameAr: "تلمسان", region: "Ouest" },
    { code: 14, name: "Tiaret", nameAr: "تيارت", region: "Ouest" },
    { code: 15, name: "Tizi Ouzou", nameAr: "تيزي وزو", region: "Centre" },
    { code: 16, name: "Alger", nameAr: "الجزائر", region: "Centre" },
    { code: 17, name: "Djelfa", nameAr: "الجلفة", region: "Centre" },
    { code: 18, name: "Jijel", nameAr: "جيجل", region: "Est" },
    { code: 19, name: "Sétif", nameAr: "سطيف", region: "Est" },
    { code: 20, name: "Saïda", nameAr: "سعيدة", region: "Ouest" },
    { code: 21, name: "Skikda", nameAr: "سكيكدة", region: "Est" },
    { code: 22, name: "Sidi Bel Abbès", nameAr: "سيدي بلعباس", region: "Ouest" },
    { code: 23, name: "Annaba", nameAr: "عنابة", region: "Est" },
    { code: 24, name: "Guelma", nameAr: "قالمة", region: "Est" },
    { code: 25, name: "Constantine", nameAr: "قسنطينة", region: "Est" },
    { code: 26, name: "Médéa", nameAr: "المدية", region: "Centre" },
    { code: 27, name: "Mostaganem", nameAr: "مستغانم", region: "Ouest" },
    { code: 28, name: "M'Sila", nameAr: "المسيلة", region: "Centre" },
    { code: 29, name: "Mascara", nameAr: "معسكر", region: "Ouest" },
    { code: 30, name: "Ouargla", nameAr: "ورقلة", region: "Sud" },
    { code: 31, name: "Oran", nameAr: "وهران", region: "Ouest" },
    { code: 32, name: "El Bayadh", nameAr: "البيض", region: "Ouest" },
    { code: 33, name: "Illizi", nameAr: "إليزي", region: "Sud" },
    { code: 34, name: "Bordj Bou Arréridj", nameAr: "برج بوعريريج", region: "Centre" },
    { code: 35, name: "Boumerdès", nameAr: "بومرداس", region: "Centre" },
    { code: 36, name: "El Tarf", nameAr: "الطارف", region: "Est" },
    { code: 37, name: "Tindouf", nameAr: "تندوف", region: "Sud" },
    { code: 38, name: "Tissemsilt", nameAr: "تيسمسيلت", region: "Ouest" },
    { code: 39, name: "El Oued", nameAr: "الوادي", region: "Sud" },
    { code: 40, name: "Khenchela", nameAr: "خنشلة", region: "Est" },
    { code: 41, name: "Souk Ahras", nameAr: "سوق أهراس", region: "Est" },
    { code: 42, name: "Tipaza", nameAr: "تيبازة", region: "Centre" },
    { code: 43, name: "Mila", nameAr: "ميلة", region: "Est" },
    { code: 44, name: "Aïn Defla", nameAr: "عين الدفلى", region: "Centre" },
    { code: 45, name: "Naâma", nameAr: "النعامة", region: "Ouest" },
    { code: 46, name: "Aïn Témouchent", nameAr: "عين تموشنت", region: "Ouest" },
    { code: 47, name: "Ghardaïa", nameAr: "غرداية", region: "Sud" },
    { code: 48, name: "Relizane", nameAr: "غليزان", region: "Ouest" },
    { code: 49, name: "Timimoun", nameAr: "تيميمون", region: "Sud" },
    { code: 50, name: "Bordj Badji Mokhtar", nameAr: "برج باجي مختار", region: "Sud" },
    { code: 51, name: "Ouled Djellal", nameAr: "أولاد جلال", region: "Sud" },
    { code: 52, name: "Béni Abbès", nameAr: "بني عباس", region: "Sud" },
    { code: 53, name: "In Salah", nameAr: "عين صالح", region: "Sud" },
    { code: 54, name: "In Guezzam", nameAr: "عين قزام", region: "Sud" },
    { code: 55, name: "Touggourt", nameAr: "تقرت", region: "Sud" },
    { code: 56, name: "Djanet", nameAr: "جانت", region: "Sud" },
    { code: 57, name: "El M'Ghair", nameAr: "المغير", region: "Sud" },
    { code: 58, name: "El Menia", nameAr: "المنيعة", region: "Sud" },
  ]).returning();

  console.log(`✅ Inserted ${wilayas.length} wilayas`);

  // Seed Categories
  const categories = await db.insert(categoriesTable).values([
    { name: "Électronique", nameAr: "إلكترونيات", icon: "💻" },
    { name: "Immobilier", nameAr: "عقارات", icon: "🏠" },
    { name: "Véhicules", nameAr: "سيارات", icon: "🚗" },
    { name: "Vêtements & Mode", nameAr: "ملابس وأزياء", icon: "👗" },
    { name: "Électroménager", nameAr: "أجهزة منزلية", icon: "🏠" },
    { name: "Meubles & Décoration", nameAr: "أثاث وديكور", icon: "🪑" },
    { name: "Alimentation", nameAr: "مواد غذائية", icon: "🥗" },
    { name: "Téléphones", nameAr: "هواتف", icon: "📱" },
    { name: "Sport & Loisirs", nameAr: "رياضة وترفيه", icon: "⚽" },
    { name: "Livres & Éducation", nameAr: "كتب وتعليم", icon: "📚" },
    { name: "Beauté & Santé", nameAr: "جمال وصحة", icon: "💄" },
    { name: "Services", nameAr: "خدمات", icon: "🔧" },
    { name: "Artisanat", nameAr: "حرف يدوية", icon: "🎨" },
    { name: "Bijouterie", nameAr: "مجوهرات", icon: "💍" },
    { name: "Agriculture", nameAr: "زراعة", icon: "🌱" },
  ]).returning();

  console.log(`✅ Inserted ${categories.length} categories`);

  const catMap: Record<string, number> = {};
  for (const c of categories) catMap[c.name] = c.id;

  const wilayas16 = wilayas.find(w => w.code === 16)!.id; // Alger
  const wilayas31 = wilayas.find(w => w.code === 31)!.id; // Oran
  const wilayas25 = wilayas.find(w => w.code === 25)!.id; // Constantine
  const wilayas19 = wilayas.find(w => w.code === 19)!.id; // Sétif
  const wilayas9  = wilayas.find(w => w.code === 9)!.id;  // Blida
  const wilayas6  = wilayas.find(w => w.code === 6)!.id;  // Béjaïa
  const wilayas13 = wilayas.find(w => w.code === 13)!.id; // Tlemcen
  const wilayas23 = wilayas.find(w => w.code === 23)!.id; // Annaba
  const wilayas15 = wilayas.find(w => w.code === 15)!.id; // Tizi Ouzou
  const wilayas35 = wilayas.find(w => w.code === 35)!.id; // Boumerdès

  // Seed Stores
  const stores = await db.insert(storesTable).values([
    {
      name: "Techno Alger",
      nameAr: "تكنو الجزائر",
      description: "Le meilleur magasin d'électronique à Alger. Nous proposons les dernières technologies au meilleur prix.",
      wilayaId: wilayas16,
      categoryId: catMap["Électronique"],
      phone: "+213 21 45 67 89",
      email: "contact@techno-alger.dz",
      website: "www.techno-alger.dz",
      address: "12 Rue Didouche Mourad, Alger Centre",
      openingHours: "Sam-Jeu: 9h-18h",
      rating: 4.7,
      reviewCount: 324,
      isVerified: true,
      isFeatured: true,
    },
    {
      name: "Galaxy Phones Oran",
      nameAr: "غالاكسي فونز وهران",
      description: "Spécialiste en téléphones mobiles et accessoires à Oran. Réparation et vente.",
      wilayaId: wilayas31,
      categoryId: catMap["Téléphones"],
      phone: "+213 41 23 45 67",
      email: "info@galaxyphones-oran.dz",
      address: "Rue Larbi Ben M'hidi, Oran",
      openingHours: "Sam-Jeu: 9h-19h",
      rating: 4.5,
      reviewCount: 187,
      isVerified: true,
      isFeatured: true,
    },
    {
      name: "Moda Alger Fashion",
      nameAr: "مودا الجزائر للأزياء",
      description: "La mode algérienne et internationale. Robes, vêtements traditionnels et contemporains.",
      wilayaId: wilayas16,
      categoryId: catMap["Vêtements & Mode"],
      phone: "+213 21 87 65 43",
      email: "moda.alger@gmail.com",
      address: "Centre Commercial Bab Ezzouar, Alger",
      openingHours: "Sam-Ven: 10h-20h",
      rating: 4.3,
      reviewCount: 210,
      isVerified: true,
      isFeatured: false,
    },
    {
      name: "Mobilier Constantine",
      nameAr: "أثاث قسنطينة",
      description: "Meubles de qualité fabriqués localement à Constantine. Salons, chambres, cuisine.",
      wilayaId: wilayas25,
      categoryId: catMap["Meubles & Décoration"],
      phone: "+213 31 12 34 56",
      email: "mobilier.constantine@dz.com",
      address: "Zone industrielle Palma, Constantine",
      openingHours: "Sam-Jeu: 8h-17h",
      rating: 4.6,
      reviewCount: 98,
      isVerified: true,
      isFeatured: false,
    },
    {
      name: "Électro Sétif",
      nameAr: "إيليكترو سطيف",
      description: "Vente d'électroménager et matériel électrique. Livraison disponible dans toute la wilaya.",
      wilayaId: wilayas19,
      categoryId: catMap["Électroménager"],
      phone: "+213 36 78 90 12",
      address: "Boulevard de l'ALN, Sétif",
      openingHours: "Sam-Jeu: 9h-18h",
      rating: 4.2,
      reviewCount: 145,
      isVerified: false,
      isFeatured: false,
    },
    {
      name: "Bio Kabyle Béjaïa",
      nameAr: "بيو قبائل بجاية",
      description: "Produits biologiques et naturels de Kabylie. Huile d'olive, miel, herbes aromatiques.",
      wilayaId: wilayas6,
      categoryId: catMap["Alimentation"],
      phone: "+213 34 45 67 89",
      email: "bio.kabyle@gmail.com",
      website: "www.bio-kabyle.dz",
      address: "Route de Bgayet, Béjaïa",
      openingHours: "Sam-Jeu: 8h-18h, Ven: 8h-12h",
      rating: 4.9,
      reviewCount: 432,
      isVerified: true,
      isFeatured: true,
    },
    {
      name: "Auto Parts Oran",
      nameAr: "قطع غيار وهران",
      description: "Pièces détachées automobiles toutes marques. Original et compatible. Livraison nationale.",
      wilayaId: wilayas31,
      categoryId: catMap["Véhicules"],
      phone: "+213 41 99 88 77",
      address: "Hay Es-Sabah, Oran",
      openingHours: "Sam-Jeu: 8h30-18h",
      rating: 4.1,
      reviewCount: 73,
      isVerified: false,
      isFeatured: false,
    },
    {
      name: "Librairie El Maarifa",
      nameAr: "مكتبة المعرفة",
      description: "Livres scolaires, universitaires et de culture générale. Papeterie et fournitures.",
      wilayaId: wilayas25,
      categoryId: catMap["Livres & Éducation"],
      phone: "+213 31 56 78 90",
      address: "Rue des Frères Boussouf, Constantine",
      openingHours: "Sam-Jeu: 8h-18h",
      rating: 4.4,
      reviewCount: 167,
      isVerified: true,
      isFeatured: false,
    },
    {
      name: "Bijouterie Tlemcen Or",
      nameAr: "مجوهرات تلمسان للذهب",
      description: "Bijouterie traditionnelle algérienne. Or, argent, bijoux berbères. Fabrication sur mesure.",
      wilayaId: wilayas13,
      categoryId: catMap["Bijouterie"],
      phone: "+213 43 21 43 21",
      email: "bijoux.tlemcen@dz.com",
      address: "Médina de Tlemcen, Place Méchouar",
      openingHours: "Sam-Jeu: 9h-19h",
      rating: 4.8,
      reviewCount: 256,
      isVerified: true,
      isFeatured: true,
    },
    {
      name: "Sport & Fitness Alger",
      nameAr: "الرياضة والياقة البدنية الجزائر",
      description: "Équipements sportifs professionnels et de loisirs. Football, musculation, natation.",
      wilayaId: wilayas16,
      categoryId: catMap["Sport & Loisirs"],
      phone: "+213 21 34 56 78",
      email: "sport.fitness.alger@gmail.com",
      address: "Hydra, Alger",
      openingHours: "Sam-Ven: 9h-20h",
      rating: 4.3,
      reviewCount: 119,
      isVerified: true,
      isFeatured: false,
    },
    {
      name: "Artisanat Kabyle Tizi Ouzou",
      nameAr: "الحرف التقليدية القبائلية تيزي وزو",
      description: "Poterie, tapis berbères, bijoux et vêtements traditionnels kabyles. Produits 100% authentiques.",
      wilayaId: wilayas15,
      categoryId: catMap["Artisanat"],
      phone: "+213 26 12 34 56",
      address: "Village artisanal Aït Hichem, Tizi Ouzou",
      openingHours: "Tous les jours: 9h-18h",
      rating: 4.9,
      reviewCount: 388,
      isVerified: true,
      isFeatured: true,
    },
    {
      name: "Beauté & Soins Annaba",
      nameAr: "تجميل وعناية عنابة",
      description: "Cosmétiques, soins naturels et produits de beauté. Marques locales et importées.",
      wilayaId: wilayas23,
      categoryId: catMap["Beauté & Santé"],
      phone: "+213 38 45 67 89",
      address: "Seraïdi, Annaba",
      openingHours: "Sam-Jeu: 9h-18h",
      rating: 4.2,
      reviewCount: 84,
      isVerified: false,
      isFeatured: false,
    },
    {
      name: "PC & Réseaux Blida",
      nameAr: "حاسوب وشبكات البليدة",
      description: "Matériel informatique, réseaux, maintenance et réparation. Service professionnel.",
      wilayaId: wilayas9,
      categoryId: catMap["Électronique"],
      phone: "+213 25 67 89 01",
      email: "pc.reseaux.blida@gmail.com",
      address: "Avenue de l'Indépendance, Blida",
      openingHours: "Sam-Jeu: 9h-18h",
      rating: 4.6,
      reviewCount: 143,
      isVerified: true,
      isFeatured: false,
    },
    {
      name: "Agri-Bio Boumerdès",
      nameAr: "زراعة طبيعية بومرداس",
      description: "Produits agricoles frais de la région. Légumes, fruits, plants et semences biologiques.",
      wilayaId: wilayas35,
      categoryId: catMap["Agriculture"],
      phone: "+213 24 56 78 90",
      address: "Route nationale 5, Boumerdès",
      openingHours: "Sam-Jeu: 7h-17h",
      rating: 4.5,
      reviewCount: 201,
      isVerified: true,
      isFeatured: false,
    },
    {
      name: "Immobilier Alger Premium",
      nameAr: "عقارات الجزائر بريميوم",
      description: "Agence immobilière spécialisée dans la vente et location. Appartements, villas, locaux commerciaux.",
      wilayaId: wilayas16,
      categoryId: catMap["Immobilier"],
      phone: "+213 21 98 76 54",
      email: "contact@immo-alger-premium.dz",
      website: "www.immo-alger-premium.dz",
      address: "Rue Abane Ramdane, Alger Centre",
      openingHours: "Dim-Jeu: 8h30-17h30",
      rating: 4.4,
      reviewCount: 312,
      isVerified: true,
      isFeatured: true,
    },
  ]).returning();

  console.log(`✅ Inserted ${stores.length} stores`);

  // Build store map
  const storeMap: Record<string, number> = {};
  for (const s of stores) storeMap[s.name] = s.id;

  // Seed Listings - Rich data
  const listings = await db.insert(listingsTable).values([
    // Electronics
    {
      title: "Samsung Galaxy S24 Ultra - Neuf",
      titleAr: "سامسونج جالكسي S24 الترا - جديد",
      description: "Samsung Galaxy S24 Ultra 256GB, Titanium Black. Garantie 1 an. Livraison disponible sur Alger.",
      price: 195000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400",
      storeId: storeMap["Techno Alger"],
      categoryId: catMap["Téléphones"],
      wilayaId: wilayas16,
      condition: "new",
      isFeatured: true,
      isNegotiable: false,
    },
    {
      title: "MacBook Pro M3 14 pouces",
      titleAr: "ماك بوك برو M3 14 بوصة",
      description: "Apple MacBook Pro 14\" M3, 16GB RAM, 512GB SSD. Parfait état, sous garantie Apple Care.",
      price: 320000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400",
      storeId: storeMap["Techno Alger"],
      categoryId: catMap["Électronique"],
      wilayaId: wilayas16,
      condition: "new",
      isFeatured: true,
      isNegotiable: true,
    },
    {
      title: "PC Gaming RTX 4070 Super",
      titleAr: "حاسوب ألعاب RTX 4070 سوبر",
      description: "Tour gaming complète: i7-13700K, RTX 4070 Super 12GB, 32GB RAM DDR5, 1TB NVMe. Prêt à jouer.",
      price: 280000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=400",
      storeId: storeMap["PC & Réseaux Blida"],
      categoryId: catMap["Électronique"],
      wilayaId: wilayas9,
      condition: "new",
      isFeatured: false,
      isNegotiable: true,
    },
    {
      title: "iPhone 15 Pro Max 256GB",
      titleAr: "آيفون 15 برو ماكس 256 جيجا",
      description: "iPhone 15 Pro Max Natural Titanium, 256GB. Tout neuf, double SIM physique.",
      price: 230000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400",
      storeId: storeMap["Galaxy Phones Oran"],
      categoryId: catMap["Téléphones"],
      wilayaId: wilayas31,
      condition: "new",
      isFeatured: true,
      isNegotiable: false,
    },
    {
      title: "Xiaomi Redmi Note 13 Pro",
      titleAr: "شاومي ريدمي نوت 13 برو",
      description: "Xiaomi Redmi Note 13 Pro 256GB/8GB RAM. Écran AMOLED 200MP. Neuf sous blister.",
      price: 68000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400",
      storeId: storeMap["Galaxy Phones Oran"],
      categoryId: catMap["Téléphones"],
      wilayaId: wilayas31,
      condition: "new",
      isFeatured: false,
      isNegotiable: true,
    },
    {
      title: "Samsung 65\" QLED 4K Smart TV",
      titleAr: "سامسونج 65 بوصة QLED 4K",
      description: "Téléviseur Samsung 65\" QLED 4K Smart TV 2024. Quantum HDR, Dolby Atmos, WiFi 6.",
      price: 145000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1593359677879-a4bb92f4834f?w=400",
      storeId: storeMap["Électro Sétif"],
      categoryId: catMap["Électroménager"],
      wilayaId: wilayas19,
      condition: "new",
      isFeatured: false,
      isNegotiable: true,
    },
    {
      title: "Laptop Lenovo ThinkPad L15",
      titleAr: "لابتوب لينوفو ثينك باد L15",
      description: "ThinkPad L15 Gen 4, Ryzen 5 7530U, 16GB RAM, 512GB SSD. Idéal pour professionnels.",
      price: 115000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400",
      storeId: storeMap["PC & Réseaux Blida"],
      categoryId: catMap["Électronique"],
      wilayaId: wilayas9,
      condition: "new",
      isFeatured: false,
      isNegotiable: false,
    },

    // Clothing & Fashion
    {
      title: "Robe Kabyle Traditionnelle Brodée",
      titleAr: "فستان قبائلي تقليدي مطرز",
      description: "Magnifique robe kabyle brodée à la main. Tissu de qualité supérieure. Tailles disponibles: S, M, L, XL.",
      price: 12500,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400",
      storeId: storeMap["Artisanat Kabyle Tizi Ouzou"],
      categoryId: catMap["Vêtements & Mode"],
      wilayaId: wilayas15,
      condition: "new",
      isFeatured: true,
      isNegotiable: false,
    },
    {
      title: "Burnous en Laine - Artisanat",
      titleAr: "برنوس صوف - حرف يدوية",
      description: "Burnous traditionnel en pure laine, tissage artisanal. Chaud et élégant. Idéal pour l'hiver.",
      price: 8500,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400",
      storeId: storeMap["Artisanat Kabyle Tizi Ouzou"],
      categoryId: catMap["Vêtements & Mode"],
      wilayaId: wilayas15,
      condition: "new",
      isFeatured: false,
      isNegotiable: true,
    },
    {
      title: "Collection Printemps Femme 2024",
      titleAr: "مجموعة ربيع المرأة 2024",
      description: "Nouvelles robes et tenues de printemps. Modèles variés, couleurs vives. Tissus légers et confortables.",
      price: 4500,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=400",
      storeId: storeMap["Moda Alger Fashion"],
      categoryId: catMap["Vêtements & Mode"],
      wilayaId: wilayas16,
      condition: "new",
      isFeatured: false,
      isNegotiable: false,
    },

    // Furniture
    {
      title: "Salon Oriental Complet 7 Pièces",
      titleAr: "صالون شرقي كامل 7 قطع",
      description: "Salon oriental traditionnel, 7 pièces, tissu velours premium, couleur bordeaux. Fabrication locale Constantine.",
      price: 85000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400",
      storeId: storeMap["Mobilier Constantine"],
      categoryId: catMap["Meubles & Décoration"],
      wilayaId: wilayas25,
      condition: "new",
      isFeatured: true,
      isNegotiable: true,
    },
    {
      title: "Chambre à Coucher Complète",
      titleAr: "غرفة نوم كاملة",
      description: "Chambre à coucher complète: lit double 160x200, 2 tables de nuit, armoire 4 portes, coiffeuse. Bois massif.",
      price: 125000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=400",
      storeId: storeMap["Mobilier Constantine"],
      categoryId: catMap["Meubles & Décoration"],
      wilayaId: wilayas25,
      condition: "new",
      isFeatured: false,
      isNegotiable: true,
    },
    {
      title: "Cuisine Équipée Moderne",
      titleAr: "مطبخ مجهز عصري",
      description: "Cuisine équipée sur mesure: meubles haut et bas, plan de travail granit, électroménager inclus.",
      price: 350000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400",
      storeId: storeMap["Mobilier Constantine"],
      categoryId: catMap["Meubles & Décoration"],
      wilayaId: wilayas25,
      condition: "new",
      isFeatured: false,
      isNegotiable: true,
    },

    // Food & Agriculture
    {
      title: "Huile d'Olive Extra Vierge Kabyle 5L",
      titleAr: "زيت زيتون بكر ممتاز قبائلي 5 لتر",
      description: "Huile d'olive extra vierge 100% naturelle, récoltée et pressée à froid. Région de Béjaïa. Bouteille 5L.",
      price: 3500,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400",
      storeId: storeMap["Bio Kabyle Béjaïa"],
      categoryId: catMap["Alimentation"],
      wilayaId: wilayas6,
      condition: "new",
      isFeatured: true,
      isNegotiable: false,
    },
    {
      title: "Miel Naturel de Montagne 1kg",
      titleAr: "عسل طبيعي جبلي 1 كيلو",
      description: "Miel pur de montagne, récolté artisanalement en Kabylie. Antibiotique naturel, goût exceptionnel.",
      price: 2800,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400",
      storeId: storeMap["Bio Kabyle Béjaïa"],
      categoryId: catMap["Alimentation"],
      wilayaId: wilayas6,
      condition: "new",
      isFeatured: false,
      isNegotiable: false,
    },
    {
      title: "Plants de Tomates Bio - 50 unités",
      titleAr: "شتلات طماطم عضوية - 50 وحدة",
      description: "Plants de tomates biologiques, variété locale résistante. Prêts à planter. Livraison en région Alger.",
      price: 1500,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1592921870583-aeafb0639ffe?w=400",
      storeId: storeMap["Agri-Bio Boumerdès"],
      categoryId: catMap["Agriculture"],
      wilayaId: wilayas35,
      condition: "new",
      isFeatured: false,
      isNegotiable: true,
    },

    // Jewelry
    {
      title: "Parure Or 18 Carats - Style Berbère",
      titleAr: "طقم ذهب 18 قيراط - طراز بربري",
      description: "Magnifique parure en or 18 carats: collier + bracelet + boucles d'oreilles. Style traditionnel algérien. Certificat d'authenticité.",
      price: 145000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400",
      storeId: storeMap["Bijouterie Tlemcen Or"],
      categoryId: catMap["Bijouterie"],
      wilayaId: wilayas13,
      condition: "new",
      isFeatured: true,
      isNegotiable: false,
    },
    {
      title: "Bague Argent Kabyle Artisanale",
      titleAr: "خاتم فضة قبائلي يدوي",
      description: "Bague en argent massif 925, motifs berbères gravés à la main. Bijou unique, réalisé par artisan certifié.",
      price: 4500,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1584302179602-e4c3d3fd629d?w=400",
      storeId: storeMap["Bijouterie Tlemcen Or"],
      categoryId: catMap["Bijouterie"],
      wilayaId: wilayas13,
      condition: "new",
      isFeatured: false,
      isNegotiable: false,
    },

    // Real Estate
    {
      title: "Appartement F4 - Alger Centre",
      titleAr: "شقة F4 - وسط الجزائر",
      description: "Appartement F4 de 105m², vue mer, bien ensoleillé. 3 chambres, salon, cuisine équipée. Résidence sécurisée avec gardien.",
      price: 12500000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400",
      storeId: storeMap["Immobilier Alger Premium"],
      categoryId: catMap["Immobilier"],
      wilayaId: wilayas16,
      condition: "new",
      isFeatured: true,
      isNegotiable: true,
    },
    {
      title: "Local Commercial - Oran Centre",
      titleAr: "محل تجاري - وسط وهران",
      description: "Local commercial 80m² au rez-de-chaussée, rue principale, fort passage piéton. Idéal pour commerce.",
      price: 5500000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=400",
      storeId: storeMap["Immobilier Alger Premium"],
      categoryId: catMap["Immobilier"],
      wilayaId: wilayas31,
      condition: "new",
      isFeatured: false,
      isNegotiable: true,
    },

    // Vehicles
    {
      title: "Renault Clio 5 RS Line 2023",
      titleAr: "رونو كليو 5 RS لاين 2023",
      description: "Renault Clio 5 RS Line 2023, 1.0 TCe 90ch, 15000km. Blanc métal, jamais accidentée. Carnet à jour.",
      price: 2850000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=400",
      storeId: storeMap["Auto Parts Oran"],
      categoryId: catMap["Véhicules"],
      wilayaId: wilayas31,
      condition: "used",
      isFeatured: true,
      isNegotiable: true,
    },
    {
      title: "Toyota Corolla 2022 - Diesel",
      titleAr: "تويوتا كورولا 2022 - ديزل",
      description: "Toyota Corolla 2022 diesel, 70000km, parfait état. 1 seul propriétaire. Tous les entretiens à la concession.",
      price: 3200000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400",
      storeId: storeMap["Auto Parts Oran"],
      categoryId: catMap["Véhicules"],
      wilayaId: wilayas31,
      condition: "used",
      isFeatured: false,
      isNegotiable: true,
    },

    // Sports
    {
      title: "Vélo VTT Professional 29\" XC",
      titleAr: "دراجة جبلية احترافية 29 بوصة",
      description: "VTT 29 pouces, cadre aluminium, Shimano 21 vitesses, fourche suspendue. Idéal pour trails algériens.",
      price: 55000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
      storeId: storeMap["Sport & Fitness Alger"],
      categoryId: catMap["Sport & Loisirs"],
      wilayaId: wilayas16,
      condition: "new",
      isFeatured: false,
      isNegotiable: false,
    },
    {
      title: "Banc de Musculation Multifonctions",
      titleAr: "مقعد رياضي متعدد الوظائف",
      description: "Station de musculation complète avec poids inclus. 50+ exercices possibles. Parfait pour salle de sport maison.",
      price: 35000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400",
      storeId: storeMap["Sport & Fitness Alger"],
      categoryId: catMap["Sport & Loisirs"],
      wilayaId: wilayas16,
      condition: "new",
      isFeatured: false,
      isNegotiable: true,
    },

    // Books
    {
      title: "Bibliothèque Scolaire Complète BEM 2024",
      titleAr: "مكتبة مدرسية كاملة BEM 2024",
      description: "Ensemble complet de livres pour la préparation au BEM 2024. Toutes les matières, fiches de révision incluses.",
      price: 4200,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400",
      storeId: storeMap["Librairie El Maarifa"],
      categoryId: catMap["Livres & Éducation"],
      wilayaId: wilayas25,
      condition: "new",
      isFeatured: false,
      isNegotiable: false,
    },
    {
      title: "Tapis Berbère Fait Main - 200x300cm",
      titleAr: "سجادة بربرية يدوية - 200×300 سم",
      description: "Authentique tapis berbère tissé à la main, laine naturelle teinte aux plantes. Motifs géométriques traditionnels.",
      price: 45000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1575301530894-f1e80ab0a1c7?w=400",
      storeId: storeMap["Artisanat Kabyle Tizi Ouzou"],
      categoryId: catMap["Artisanat"],
      wilayaId: wilayas15,
      condition: "new",
      isFeatured: true,
      isNegotiable: true,
    },
    {
      title: "Poterie Kabyle Décorative - Set 6 pièces",
      titleAr: "فخار قبائلي زخرفي - مجموعة 6 قطع",
      description: "Ensemble de 6 pièces en poterie kabyle peintes à la main. Vases, bols, assiettes décoratives. Pièces uniques.",
      price: 8500,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400",
      storeId: storeMap["Artisanat Kabyle Tizi Ouzou"],
      categoryId: catMap["Artisanat"],
      wilayaId: wilayas15,
      condition: "new",
      isFeatured: false,
      isNegotiable: false,
    },
    {
      title: "Crème Argan Naturelle Bio 100ml",
      titleAr: "كريم أرغان طبيعي عضوي 100 مل",
      description: "Crème à l'huile d'argan pure, anti-âge et hydratante. Fabriquée en Algérie, sans conservateurs chimiques.",
      price: 1800,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400",
      storeId: storeMap["Beauté & Soins Annaba"],
      categoryId: catMap["Beauté & Santé"],
      wilayaId: wilayas23,
      condition: "new",
      isFeatured: false,
      isNegotiable: false,
    },
    {
      title: "Réfrigérateur Samsung No Frost 420L",
      titleAr: "ثلاجة سامسونج نو فروست 420 لتر",
      description: "Réfrigérateur Samsung combiné 420L No Frost, A++, distributeur d'eau. Couleur inox. Garantie 2 ans.",
      price: 89000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=400",
      storeId: storeMap["Électro Sétif"],
      categoryId: catMap["Électroménager"],
      wilayaId: wilayas19,
      condition: "new",
      isFeatured: false,
      isNegotiable: true,
    },
    {
      title: "Machine à Laver Condor 8kg",
      titleAr: "غسالة كوندور 8 كيلو",
      description: "Machine à laver frontale Condor 8kg, 1200 tr/min, A+++, 15 programmes. Marque algérienne fiable.",
      price: 42000,
      currency: "DZD",
      imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
      storeId: storeMap["Électro Sétif"],
      categoryId: catMap["Électroménager"],
      wilayaId: wilayas19,
      condition: "new",
      isFeatured: false,
      isNegotiable: false,
    },
  ]).returning();

  console.log(`✅ Inserted ${listings.length} listings`);
  console.log("🎉 Seeding complete!");
}

seed().catch((err) => {
  console.error("❌ Seeding failed:", err);
  process.exit(1);
});
